src/puppetlabs/trapperkeeper/logging.clj

In addition to file path, take java.io.File, java.net.URL, java.io.InputStream, or org.xml.sax.InputSource as allowed by the underlying JoranConfigurator.
- Rename configure-logger-via-file! to configure-logger! and surrounding function args accordingly.
See Jira TK-131.

Relax configure-logger! preconditions to take more than a file path string

---

src/puppetlabs/trapperkeeper/logging.clj

Previously, the `configure-logger!` function had a precondition asserting that
the `logging-conf` argument passed to it matched one of five different types.
The argument is passed through to the `doConfigure` method for the
JoranConfigurator class.
The benefit to having the precondition is a more explicit error message in the
case where `logging-conf` is of a type that `doConfigure` doesn't accept.
However, the downside to this is that we have to have a long list of all the
possibilities, which we previously got wrong, thereby artificially
constraining what could be used to configure logging. Thus, this commit
removes the precondition completely and updates the relevant docstring.
With this change, the error message if an argument of incorrect
type is used is not very informative: …

(TK-131) Remove precondition from `configure-logger!`

---

project.clj

The prismatic/plumbing and prismatic/schema library dependencies are
lagging behind the latest stable version. This will increasingly
cause conflicts in trapperkeeper projects. This patch updates the
dependencies to the latest stable versions.
* Update project.clj dependencies

(TK-197) Update prismatic library dependencies

---

src/puppetlabs/trapperkeeper/core.clj

Explicitly rethrowing the pending exception adds another wrapper,
whereas (throw+) just passes on the existing exception.
The relevant bit from the throw+ docstring:
Within a try+ catch clause, a throw+ call with no arguments rethrows
the caught object within its original (possibly nested) wrappers.

(maint) Preserve stack, etc. when rethrowing in main

---

README.md

This commit adds a Support section at the bottom of the README that
includes a link to the JIRA project and the IRC and Gitter channels.

(PE-11023) Add Support section to README

---

test/puppetlabs/trapperkeeper/logging_test.clj
test/puppetlabs/trapperkeeper/testutils/logging.clj

Previously, logs-matching only filtered based on the log message and
given regex. The logged? assertion then checked to ensure there was
exactly 1 matching log line before considering the specified
log level. This led to the assertion failing in situations where
more than one log message matched even if one of the matches was at a
different level than the one specified in the assertion.

Refactor testutils.logging/logs-matching to match on message and level.

---

src/puppetlabs/trapperkeeper/logging.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj
test/puppetlabs/trapperkeeper/logging_test.clj
test/puppetlabs/trapperkeeper/testutils/logging.clj
test/puppetlabs/trapperkeeper/testutils/logging_test.clj

Rework testutils.logging to tie in at the logback (Java) level, rather
than the clojure.tools.logging level, allowing us to see and manipulate
most, if not all log events.
Have the core API handle only native event objects for efficiency, but
provide a more friendly map representation via event->map.
Add a set of scoped call-with-* and with-* handlers to allow temporarily
overriding the logging appenders, level, etc.
Rework the existing with-test-logging, with-test-logging-debug, and
logged? code to use the new API, add some tests, and add some minor new,
backward-compatible features.  Using the new API does change the
fundamental semantics a bit, since logged? may see more events than it
used to (perhaps from ActiveMQ or...), but that seems unlikely to break
existing tests unless the the …

(TK-291) Handle all events in testutils.logging

---

.gitignore
project.clj
src/puppetlabs/trapperkeeper/services.clj
src/puppetlabs/trapperkeeper/services_internal.clj
test/puppetlabs/trapperkeeper/optional_deps_test.clj

This PR does the following:
* Upgrades the version of schema we use
* Uses schema to validate things in services-internal
* Adds support for optional dependencies; namely, transformation of an
alternative dependency specification into a form Prismatic Graph can
understand and adding a helper function for determining if a service
has been included.
This commit is purely additive; no breaking changes are introduced.
This work represents the absolute minimum of work required to make this
a usable feature; while additive improvements may be made, the things
exposed here are not expected to change.
**Important notes**
* There are some functions marked with a TODO about turning them into schemas; I think the whole validation flow in `services-internal` can be drastically simplified into a …

Optional Dependencies

---

project.clj
src/puppetlabs/trapperkeeper/app.clj
src/puppetlabs/trapperkeeper/config.clj
src/puppetlabs/trapperkeeper/core.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/services_test.clj
test/puppetlabs/trapperkeeper/testutils/bootstrap.clj

This PR adds a restart function for TK apps that allows trapperkeeper to cleanly handle SIGHUP by calling restart on all of the registered apps.

(TK-202) Add support for restart and HUP handling

---

test/puppetlabs/trapperkeeper/services_test.clj

The recent changes related to HUP support have a test that
sends a HUP signal and then waits for some period of time
to validate that the restart behavior took effect.  The initial
commit of this code appears to be using too low of a timeout
for some of our CI hardware.
This commit bumps the timeout up from 1s to 5s.

(MAINT) increase timeout in service test

---

test/puppetlabs/trapperkeeper/services_test.clj

Unfortunately, jenkins clients swallow up HUP signals, so the previous
HUP test consistently fails in jenkins, as the signal never gets to
clojure. This commit addresses this by calling directly into the
function that is invoked by the HUP signal, which is as close as we can
get for the moment.

(TK-202) Refactor HUP test to call restart-tk-apps

---

dev-resources/logback.xml

Reverts puppetlabs/trapperkeeper#207. Tests are passing now, so this is no longer required.

Revert "(TK-202) Increase logging to debug jenkins test failure"

---

project.clj

Add log4j-over-slf4j dependency, which provides a log4j interface for slf4j so
libraries written to that interface log correctly with logback.

(TK-320) Add log4j compatibility layer

---

src/puppetlabs/trapperkeeper/services_internal.clj
test/puppetlabs/trapperkeeper/optional_deps_test.clj

Fixes a bug where the `service` macro would fail if not using a service
protocol but using the new optional dependencies binding form.

(TK-319) Handle optional dependencies w/o protocol

---

project.clj

pl-typesafe v0.1.5 contains a fix that is necessary in order to
support interpolation in hocon config files.

(HC-51) Update to pl-typesafe-0.1.5

---

test/puppetlabs/trapperkeeper/testutils/bootstrap.clj

All of the various `with-app*` macros in the tk bootstrap testutils
have a corresponding `bootstrap-services*` fn that can be used in
cases where a test needs more control over the lifecycle of the app,
except for `with-app-with-config`.  This commit simply adds a
`bootstrap-services-with-config` to achieve parity there.

(MAINT) add testutils bootstrap-services-with-config

---

dev-resources/logback.xml
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/internal_test.clj
test/puppetlabs/trapperkeeper/testutils/bootstrap.clj

FOR REVIEW: this builds on PR #221, only the final commit of this PR is interesting.  Will rebase after that is merged.
-------------------------
This commit changes the HUP/restart logic so that if there are too
many events queued up in the core.async lifecycle channel, we won't
keep piling more on.  We instead just log a warning and ignore
the HUP request.

(FOR REVIEW) (TK-326) create max number of queued hup events

---

src/puppetlabs/trapperkeeper/core.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/internal_test.clj

This commit adds/improves some debugging statements to clarify what
is happening with lifecycle events inside of TK, and when we shut
down the Clojure agent pool.
To achieve this we needed to provide a bit of schema around the
items that are put onto the core.async channel for lifecycle management.

(TK-334) debug logging for restart and shutdown

---

project.clj

This commit adds explicit dependencies on all of the logback
artifacts that we use, to ensure that they are all the same version.
This also ensures that if any downstream projects happen to bring
in a conflicting version, the conflict will be caught at build time.

(TK-344) Explicitly specify all logback dependencies

---

src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/shutdown_test.clj

This commit moves the "main" shutdown/stop logic off of the main
thread and onto the core.async worker thread.  This ensures that
we don't end up in a situation where we have restarts queued up
and then an error occurs and causes the situation where we have
lifecycle activity going on on the async worker thread while
the main thread is also trying to perform the shutdown tasks.

(TK-330) move main shutdown logic to core async worker

---

src/puppetlabs/trapperkeeper/app.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/shutdown_test.clj

This PR does the following:
* Tighten up the LifeCycleTask schema, since the `task-function` is no longer optional.
* Prioritize shutdowns over other events by adding a second core.async channel for requesting shutdowns, and using a prioritized `alts!` in the worker loop when reading off of the channel.
* Add logic to clean off any queued messages from the lifecycle channels during shutdown, so that we can ensure that no threads get stuck in a blocking `put` when we close the channels.

(TK-331) prioritize shutdowns

---

.gitmodules
project.clj

This commit adds cljfmt as a valid lein alias which will defer to the
plugin lein-cljfmt using the pl-clojure-style repo's styles.
We use a git submodule approach to pulling in pl-clojure-style to ease
the ability in the future of using the tool within an automated process
(e.g. travis-ci) and because of significant use of submodules in other
puppet labs clj projects.

(SERVER-893) Adopt pl-clojure-style

---

test/puppetlabs/trapperkeeper/testutils/logging.clj
test/puppetlabs/trapperkeeper/testutils/logging_test.clj

Previously we ignored the log-level parameter if it was supplied.
This adds test cases to ensure that logged? fails, as well as succeeds,
properly and updates the logged? matching mechanism to first filter logs
by log level if requested.

(TK-362) Honor log level in logged? macro

---

dev-resources/bootstrapping/cli/bootstrap_with_comments.cfg
dev-resources/bootstrapping/cli/duplicate_services.cfg
dev-resources/bootstrapping/cli/duplicate_services/duplicates.cfg
dev-resources/bootstrapping/cli/duplicate_services/split_one.cfg
dev-resources/bootstrapping/cli/duplicate_services/split_two.cfg
dev-resources/bootstrapping/cli/fake_namespace_bootstrap.cfg
dev-resources/bootstrapping/cli/invalid_bootstrap.cfg
dev-resources/bootstrapping/cli/invalid_entry_bootstrap.cfg
dev-resources/bootstrapping/cli/invalid_service_graph_bootstrap.cfg
dev-resources/bootstrapping/cli/missing_definition_bootstrap.cfg
src/puppetlabs/trapperkeeper/bootstrap.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj
test/puppetlabs/trapperkeeper/examples/bootstrapping/test_services.clj

This PR extends TK to throw an error during startup if two bootstrap
entries implement the same service protocol. Previously TK would startup the
last entry it found that implemented a protocol and silently ignore the rest.
This PR also contains additions to the bootstrap namespace to give more
information when a bootstrap related error is raised. Since bootstrap entries
can now be split up between multiple files, the error messages give the
location of the bootstrap files and the line number where the offending
service entries were included.
This functionality is implemented by passing around a list of the bootstrap
entries annotated with the file and line number they came from.
This PR also makes some changes to maintain the ability to have duplicate
bootstrap entries, since TK might …

(TK-211) Disallow duplicate protocol implementations

---

src/puppetlabs/trapperkeeper/bootstrap.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj

This commit changes the behavior of TK when a bootstrap file contains a service
entry that can't be resolved. Previous TK would throw an error and fail to
start. Now TK will log a warning and attempt to continue loading the app
This is being added to support workflows where a user might want to add a
service entry to their bootstrap before a TK app actually requires it.
TK continues to throw errors and abort if the service entry is malformed or if
the service is found, but doesn't have a valid service graph

(TK-349) Log warning when service can't be found

---

dev-resources/bootstrapping/cli/split_bootstraps/empty/empty2.cfg
src/puppetlabs/trapperkeeper/bootstrap.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj

This commit makes the empty bootstrap error less ambiguous, and includes a list
of the bootstrap files that it searched in

(TK-351) Improve empty bootstrap error message

---

CHANGELOG.md
project.clj

Bump to version 1.4.0
This is a minor feature/bugfix release
* TK-347 - Support directories and paths in TK's "bootstrap-config" CLI
argument
* TK-211 - Trapperkeeper doesn't error if two services implementing the same
protocol are started
* TK-349 - TK should not fail during startup if an unrecognized service is
found in bootstrap config
* TK-351 - Ensure all bootstrap related errors log what file they come from

(MAINT) Update changelog and bump version to 1.4.0

---

src/puppetlabs/trapperkeeper/bootstrap.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj

TK 1.4.0 introduced a regression which caused TK to fail to start if a
bootstrap file was found in a jar file on the class path.
This commit restores that functionality and adds a couple tests for the feature

(TK-375) Fix bootstrap regression

---

src/puppetlabs/trapperkeeper/services_internal.clj

This purpose of this commit is to:
- remove :pre and :post conditions 
- collapse validate-fn-forms and validate-deps-form 
- use schema to verify input/ouput

(TK-309) Schemafy TK service macro

---

src/puppetlabs/trapperkeeper/services.clj
test/puppetlabs/trapperkeeper/optional_deps_test.clj

This commit fixes defservice's sadness when specifying optional
dependencies without a protocol. The bug was from use of
clojure.tools.macro/name-with-attributes, which was mistaking the
dependency map for metadata and removing it from the forms passed on to
the service macro itself.
The remediation was to implement our own name-with-attributes that is
smart enough to ignore dependency maps and not blindly accept them as
metadata maps.
This commit also adds tests for the various permutations of input to
defservice.

(TK-382) Fix defservice + optional deps

---

src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/services_test.clj

This PR adds support for using a restart file that holds nothing but a long as a counter. This counter will increment each time a service completes its starting process.

(TK-345) add support for optional restart-file

---

.travis.yml
project.clj

This update bumps us to the latest version of logback, which includes
(among other things) support for adding thread IDs to the HTTP
access log files.

(TK-397) Update to latest version of logback

---

documentation/Command-Line-Arguments.md
documentation/Index.md
documentation/Restart-File.md
src/puppetlabs/trapperkeeper/common.clj
src/puppetlabs/trapperkeeper/config.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/core_test.clj

This PR adds the ability for the restart-file setting to be
specified via a CLI arg.  The commit preserves the ability to source the
restart-file setting from the global section in Trapperkeeper
configuration.  In the event that the setting were specified in both
places, the setting used for the CLI arg would be the one used.
This PR also includes some documentation for the restart-file feature.

(TK-405) Support specifying restart-file via a CLI arg

---

.travis.yml
CHANGELOG.md
project.clj

These commits clean up some cruft from the project.clj, and introduce the `lein-parent` plugin to allow us to inherit dependency versions from the parent project.  Also updates the CHANGELOG for a 1.5.2 release.

(SERVER-1494) introduce parent project

---

project.clj
test/puppetlabs/trapperkeeper/bootstrap_test.clj
test/puppetlabs/trapperkeeper/core_test.clj

This updates trapperkeeper to use the latest clj-parent, which brings in
some breaking changes from clj-kitchensink. These only affect the
exception thrown by `internal/parse-cli-args!`.

(maint) Update trapperkeeper to clj-parent latest

---

src/puppetlabs/trapperkeeper/internal.clj

Previously trapperkeeper would log a message when beginning to run a
lifecycle function, but not when the lifecycle function had returned.
This means that when debugging failures it can be challenging to tell
if a service has died mid-lifecycle function (depending on how much
logging that service has implemented). To alleviate that somewhat, this
commit adds a log message at debug level for when the lifecycle function
has finished.

(maint) Add log message for finishing lifecycle function

---

src/puppetlabs/trapperkeeper/core.clj

Previously, if an unhandled exception that can be coerced into a map but
that does not have a `:type` key in it were propagated up to
Trapperkeeper's main function, the exception output would be mishandled.
This commit rethrows the original exception if a nil value is found for the
`:type` key in the map, allowing the original exception output to be
displayed properly.

(TK-439) Handle exceptions having no type in main

---

project.clj

We should include a license in the project.clj so other people can depend on automation to find all this info!

(maint) Add license to the project.clj

---

project.clj
src/puppetlabs/trapperkeeper/plugins.clj
test/puppetlabs/trapperkeeper/plugins_test.clj

In Java 9 to add a jar to the classpath, we have to add a new
classloader in the hierarchy on the Thread (this is where io/resource
will look) and also to the clojure baseLoader (this is where clojure
will look for actual code). In Java 8 since the base hierarchy was
modifiable we could just change one place and it would be seen
everywhere.
I've also made the kitchensink dependency explicit, since it really does depend on this version number.

(maint) Add plugin jars to clojure's base loader

---

src/puppetlabs/trapperkeeper/internal.clj

This commit boosts the message logged by the SIGHUP handler from DEBUG to INFO.
This change makes it easy to see from logs when a SIGHUP came into the service.

(TK-466) Log SIGHUP events at INFO level

---

test/puppetlabs/trapperkeeper/testutils/logging.clj
test/puppetlabs/trapperkeeper/testutils/logging_test.clj

This commit updates testutils.logging such that the logged? assertion will
correctly match formatted log messages, such as those produced by SLF4J.
Prior to this commit, the matching machinery called .getMessage to recover
the logged message from LoggingEvent instances. The .getFormattedMessage
method is now called, which resolves format strings that may have been used.

(TK-471) Capture formatted messages in testutils.logging

---

.travis.yml
CHANGELOG.md
project.clj
src/puppetlabs/trapperkeeper/services/nrepl/nrepl_service.clj
test/puppetlabs/trapperkeeper/services/nrepl/nrepl_service_test.clj
test/puppetlabs/trapperkeeper/services/nrepl/nrepl_test_send_middleware.clj
test/puppetlabs/trapperkeeper/testutils/logging_test.clj

This is part of a series of changes to support nrepl/nrepl in trapperkeeper. It
needs to be merged after the corresponding changes in clj-parent.
This change requires lein 2.9.0 or later to work; this is when the lein project
changed from the legacy org.clojure/tools.nrepl to the supported nrepl/nrepl
line of development.
This release drops support for JDK7, as nrepl/nrepl has a minimum requirement
of JDK8.
Must not be merged until after https://github.com/puppetlabs/clj-parent/pull/167 is merged.

(orch-2282) Updates trapperkeeper to use the latest nrepl/nrepl

---

src/puppetlabs/trapperkeeper/core.clj

If a slingshot error was thrown with a `:type` value other than `:cli-help` or
`:cli-error`, the original error would be replaced by an error about a missing
clause in the case statement. This allows those errors to just be rethrown.

(maint) Fix some errors being obscured

---

.gitignore
.travis.yml
documentation/Built-in-Shutdown-Service.md
documentation/Command-Line-Arguments.md
ext/test/custom-exit-behavior
ext/test/lib/custom-exit-behavior/bootstrap.cfg
ext/test/run-all
ext/test/top-level-cli
ext/travisci/prep-macos
project.clj
src/puppetlabs/trapperkeeper/core.clj
src/puppetlabs/trapperkeeper/internal.clj
test/puppetlabs/trapperkeeper/custom_exit_behavior_test.clj
tk

This makes it possible to specify a process exit status value and final messages when calling `request-shutdown`.  The series also fixes some bugs, and adds fully "external" top-level tests.  I needed to make any number of somewhat arbitrary choices, particularly regarding the tests, and mostly leaned toward things previously done in pdb, but I'm happy to rework whatever we like.
You can try all the new tests (which for now just print *everything*, to make CI postmortems easier) by invoking this:
```
lein uberjar
ext/test/run-all
```
from the project directory.
You can also run only the custom exit status tests by invoking `ext/test/custom-exit-status` directly.  And note that particular test, unlike `top-level-cli` doesn't actually rely on the uberjar right now).
Please see the …

(PDB-4636) request-shutdown: support custom exit status/messages

---

.gitmodules
project.clj

This commit removes all references to the pl-clojure-style repo. This was used
for linting / style checking in the past, but hasn't been used for quite some
time, so no reason to keep the `cljfmt` profile for running it.

(maint) Remove pl-clojure-style linter

---

CHANGELOG.md
project.clj

Going to bump the logback version in new clj-parent release https://github.com/puppetlabs/clj-parent/pull/381 .

(PE-34726) Add slj4j-api dependency, bump clj-parent, pin logback 1.3.5 version

---

project.clj
src/puppetlabs/trapperkeeper/common.clj
src/puppetlabs/trapperkeeper/config.clj

This removes the use of clj-yaml for yaml parsing because internally it uses snakeyaml 1.33. Instead, snakeyaml 2.0 is used directly and a routine for mapping from java structures to clojure structures to clojure structures is added.

(PE-36476) Replace clj-yaml with snakeyaml 2.0

---

CHANGELOG.md
documentation/Test-Utils.md
test/puppetlabs/trapperkeeper/logging_test.clj
test/puppetlabs/trapperkeeper/testutils/logging.clj

`logged?` previously had an undocumented restriction that it would only return true if a single line matched (more than one would return false). This adds the flexibility to remove this restriction, as some log lines may legitimately be repeated.

(maint) Add flexibility to `logged?` to not only match a single line

---

.github/workflows/mend.yaml
project.clj

The java version for the mend-scan action was out of date, preventing it from functioning correctly.

(maint) update mend scan action

---

.github/workflows/clojure-linting.yaml
.github/workflows/mend.yaml

This updats the actions/checkout to the latest, setup-java to the latest, and setup-clojure to the latest to allow the mend scans to operate correctly

(maint) update versions of github actions dependencies

---

CHANGELOG.md
test/puppetlabs/trapperkeeper/testutils/logging.clj

Update the `logged?` function to only emit messages when there are
multiple statements when they aren't expected, and also clean up
the output to be more useful.

(maint) update logged? for better output, prepare for release

---

CHANGELOG.md
test/puppetlabs/trapperkeeper/testutils/logging.clj

Update the `logged?` function to only emit messages when there are
multiple statements when they aren't expected, and also clean up
the output to be more useful.

(maint) fix logging, prepare for release 
